# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProjectScanner.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(99, 40, 501, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout1 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout1.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout1.setSpacing(0)
        self.horizontalLayout1.setObjectName("horizontalLayout1")
        self.selectScanFolderBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.selectScanFolderBtn.setMinimumSize(QtCore.QSize(0, 30))
        self.selectScanFolderBtn.setIconSize(QtCore.QSize(16, 16))
        self.selectScanFolderBtn.setObjectName("selectScanFolderBtn")
        self.horizontalLayout1.addWidget(self.selectScanFolderBtn)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(100, 140, 501, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout2.setObjectName("horizontalLayout2")
        self.selectScanFoldLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.selectScanFoldLabel.setText("")
        self.selectScanFoldLabel.setObjectName("selectScanFoldLabel")
        self.horizontalLayout2.addWidget(self.selectScanFoldLabel)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(100, 250, 501, 80))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout3.setSpacing(0)
        self.horizontalLayout3.setObjectName("horizontalLayout3")
        self.selecResultFolderBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.selecResultFolderBtn.setObjectName("selecResultFolderBtn")
        self.horizontalLayout3.addWidget(self.selecResultFolderBtn)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(100, 360, 501, 80))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout4.setObjectName("horizontalLayout4")
        self.scanResultLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.scanResultLabel.setText("")
        self.scanResultLabel.setObjectName("scanResultLabel")
        self.horizontalLayout4.addWidget(self.scanResultLabel)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(100, 460, 501, 51))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scanButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.scanButton.setObjectName("scanButton")
        self.horizontalLayout.addWidget(self.scanButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.selectScanFolderBtn.setText(_translate("MainWindow", "请选择待扫描的文件夹"))
        self.selecResultFolderBtn.setText(_translate("MainWindow", "请选择扫描结果导出的文件夹"))
        self.scanButton.setText(_translate("MainWindow", "开始扫描"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
